Update web100 extended views to use web100_static table
m-lab/etl-schema pull request #137
Opened 2022-04-27 18:37 UTC by stephen-soltesz

This change updates the current web100 extended views to use the `web100_static` date partitioned table.

This change disables the `IsErrored` boolean based on `blacklist_flags` because this value was never supported by the v1 pipeline. The comment preserves a TODO to restore.

2022-04-27 18:54 UTC, stephen-soltesz commented
NOTE: this PR should not be merged until https://github.com/m-lab/etl-schema/pull/136 is deployed to production. The changes in both PRs cannot be combined at once.

2022-04-27 19:48 UTC, stephen-soltesz commented
Part of https://github.com/m-lab/etl/issues/1074

2022-04-27 21:18 UTC, mattmathis requested changes
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/137)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`views/ndt_intermediate/extended_web100_downloads.sql` line 52 at r1](https://reviewable.io/reviews/m-lab/etl-schema/137#-N0gr-yN5vAay9CJcbGb:-N0gr-yN5vAay9CJcbGc:bygy14w) ([raw file](https://github.com/m-lab/etl-schema/blob/9fbefd0daf1862f3ad6537aa4357101b69df1ef3/views/ndt_intermediate/extended_web100_downloads.sql#L52)):*
> ```TSQL
> ),
> 
> Web100UploadModels AS (
> ```

This is the wrong file.   Somehow download got overwritten by upload.  Best to go back and redo, rather than to try to fix all of the little places where upload and download are different).


<!-- Sent from Reviewable.io -->

2022-04-28 00:03 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/137)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @mattmathis)

___
*[`views/ndt_intermediate/extended_web100_downloads.sql` line 52 at r1](https://reviewable.io/reviews/m-lab/etl-schema/137#-N0gr-yN5vAay9CJcbGb:-N0hTcZU7JfLL9QX5JGZ:b-lele72) ([raw file](https://github.com/m-lab/etl-schema/blob/9fbefd0daf1862f3ad6537aa4357101b69df1ef3/views/ndt_intermediate/extended_web100_downloads.sql#L52)):*
<details><summary><i>Previously, mattmathis (Matt Mathis) wrote…</i></summary><blockquote>

This is the wrong file.   Somehow download got overwritten by upload.  Best to go back and redo, rather than to try to fix all of the little places where upload and download are different).
</blockquote></details>

Thank you for noticing that -- I'm not sure how that happened. PTAL?


<!-- Sent from Reviewable.io -->

2022-04-28 00:12 UTC, mattmathis approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-schema/137)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-04-28 14:41 UTC, merged